### PR TITLE
Gps improvements

### PR DESCRIPTION
**Pull request by TheCrazyLex**
Pretty cool,  since you use the op3 gps, all my patches cherry picked cleanly :)

### CODE REVIEW

**Comment by bmc08gt** [comment]
Fix commit titles :)

**Comment by TheCrazyLex** [comment]
@bmc08gt oh yeah, I was too happy that I didn't have to fix conflicts that I forgot that xD.

**Comment by TheCrazyLex** [comment]
Fixed

**Comment by TheCrazyLex** [comment]
Oh well, this was already merged xD

**Pull request closed without merging**
